test compile precise-output
target scry32

; Diverging control flow: CFGs with no path from some (or any) block to an
; exit. cg_clif emits these for `fn ... -> ! { loop {} }` bodies. In
; scry-core: panicking::panic_in_cleanup and panicking::eh_personality.
; Every block carries real work so blocks cannot be trivially collapsed, and
; the loops keep a live accumulator flowing across the back-edge.

; The shape rustc emits for panic_in_cleanup: a jump chain ending in a
; self-loop, no return instruction anywhere.
function %spin_chain() {
block0:
    v0 = iconst.i32 0
    jump block1(v0)

block1(v1: i32):
    v2 = iconst.i32 1
    v3 = iadd v1, v2
    jump block2(v3)

block2(v4: i32):
    v5 = iconst.i32 2
    v6 = iadd v4, v5
    jump block2(v6)
}

; VCode:
; block0:
;   Const(ty: Known(Uint(2)), rd:, v(206), imm: 0, )
;   EchoLong(rds:, v(209), rss:, v(206), out: 1, )
;   JumpIssue(link:, v(205), kind: Jump, dst: MachLabel(1), trig: 0, )
;   JumpTrigger(link:, v(205), args:, v(209), )
; block1:
;   EchoLong(rds:, v(207), rss:, v(193), out: 1, )
;   Const(ty: Known(Uint(2)), rd:, v(204), imm: 1, )
;   Alu2(var: Add, var_out LowOnly, rds:, v(203), rss:, v(207), v(204), outs: [1], )
;   JumpIssue(link:, v(202), kind: Jump, dst: MachLabel(2), trig: 0, )
;   JumpTrigger(link:, v(202), args:, v(203), )
; block2:
;   EchoLong(rds:, v(208), rss:, v(196), out: 1, )
;   Const(ty: Known(Uint(2)), rd:, v(201), imm: 2, )
;   Alu2(var: Add, var_out LowOnly, rds:, v(200), rss:, v(208), v(201), outs: [1], )
;   JumpIssue(link:, v(199), kind: Jump, dst: MachLabel(2), trig: 0, )
;   JumpTrigger(link:, v(199), args:, v(200), )
;
; Disassembled:
; block0: ; offset 0x0
; const u32, 0
; echo =>1
; nop 
; block1: ; offset 0x6
; echo =>1
; const u32, 1
; add Low =>1
; nop 
; block2: ; offset 0xe
; echo =>1
; const u32, 2
; add Low =>1
; jmp -3, 0

;; A multi-block cycle with no exit.
function %spin_cycle() {
block0:
    v0 = iconst.i32 7
    jump block1(v0)

block1(v1: i32):
    v2 = iconst.i32 1
    v3 = iadd v1, v2
    jump block2(v3)

block2(v4: i32):
    v5 = iconst.i32 3
    v6 = iadd v4, v5
    jump block1(v6)
}

; VCode:
; block0:
;   Const(ty: Known(Uint(2)), rd:, v(206), imm: 7, )
;   EchoLong(rds:, v(209), rss:, v(206), out: 1, )
;   JumpIssue(link:, v(205), kind: Jump, dst: MachLabel(1), trig: 0, )
;   JumpTrigger(link:, v(205), args:, v(209), )
; block1:
;   EchoLong(rds:, v(207), rss:, v(193), out: 1, )
;   Const(ty: Known(Uint(2)), rd:, v(204), imm: 1, )
;   Alu2(var: Add, var_out LowOnly, rds:, v(203), rss:, v(207), v(204), outs: [1], )
;   JumpIssue(link:, v(202), kind: Jump, dst: MachLabel(2), trig: 0, )
;   JumpTrigger(link:, v(202), args:, v(203), )
; block2:
;   EchoLong(rds:, v(208), rss:, v(196), out: 1, )
;   Const(ty: Known(Uint(2)), rd:, v(201), imm: 3, )
;   Alu2(var: Add, var_out LowOnly, rds:, v(200), rss:, v(208), v(201), outs: [1], )
;   JumpIssue(link:, v(199), kind: Jump, dst: MachLabel(1), trig: 0, )
;   JumpTrigger(link:, v(199), args:, v(200), )
;
; Disassembled:
; block0: ; offset 0x0
; const u32, 7
; echo =>1
; nop 
; block1: ; offset 0x6
; echo =>1
; const u32, 1
; add Low =>1
; nop 
; block2: ; offset 0xe
; echo =>1
; const u32, 3
; add Low =>1
; jmp -7, 0

;; Conditionally diverging: one path loops forever, the other returns. block2
;; uses v0 directly — a cross-block use of a dominating definition.
function %spin_cond(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 0
    brif v0, block1(v1), block2

block1(v2: i32):
    v3 = iconst.i32 1
    v4 = iadd v2, v3
    jump block1(v4)

block2:
    v5 = iconst.i32 5
    v6 = iadd v0, v5
    return v6
}

; VCode:
; block0:
;   EchoLong(rds:, v(209), rss:, v(192), out: 0, )
;   Duplicate(rd1:, v(217), rd2:, v(218), rs:, v(209), out1: 2, out2: 1, )
;   Const(ty: Known(Uint(2)), rd:, v(205), imm: 0, )
;   Reorder(rd1:, v(219), rd2:, v(220), rs1:, v(218), rs2:, v(205), out: 2, )
;   UnaryAlu(op: LogNeg, rd:, v(221), rs:, v(217), )
;   JumpIssue(link:, v(204), kind: Branch(dir: true, cond: v(221)), dst: MachLabel(2), trig: 0, )
;   JumpTrigger(link:, v(204), args:, v(220), v(219), )
; block1:
;   EchoSplit(rd1:, v(214), rd2:, v(215), rs1:, v(213), rs2:, v(208), out1: 0, out2: 2, )
;   Discard(rss:, v(214), )
;   Const(ty: Known(Uint(2)), rd:, v(203), imm: 5, )
;   Alu2(var: Add, var_out LowOnly, rds:, v(202), rss:, v(215), v(203), outs: [1], )
;   Ret(trig: 0, )
; block2:
;   EchoSplit(rd1:, v(211), rd2:, v(212), rs1:, v(206), rs2:, v(210), out1: 2, out2: 0, )
;   Discard(rss:, v(212), )
;   JumpIssue(link:, v(207), kind: Jump, dst: MachLabel(3), trig: 0, )
;   JumpTrigger(link:, v(207), args:, v(211), )
; block3:
;   EchoLong(rds:, v(216), rss:, v(194), out: 1, )
;   Const(ty: Known(Uint(2)), rd:, v(201), imm: 1, )
;   Alu2(var: Add, var_out LowOnly, rds:, v(200), rss:, v(216), v(201), outs: [1], )
;   JumpIssue(link:, v(199), kind: Jump, dst: MachLabel(3), trig: 0, )
;   JumpTrigger(link:, v(199), args:, v(200), )
;
; Disassembled:
; block0: ; offset 0x0
; echo =>0
; dup =>2, =>1
; const u32, 0
; echo =>2, =>2
; eq =>0
; jmp 5, 0
; block1: ; offset 0xc
; echo =>0, =>2
; nop 
; const u32, 5
; add Low =>1
; ret 0
; block2: ; offset 0x16
; echo =>2, =>0
; nop 
; nop 
; block3: ; offset 0x1c
; echo =>1
; const u32, 1
; add Low =>1
; jmp -3, 0

