test interpret
;test run
test compile precise-output
target scry32

function %add_sum(i32 sext, i32 uext) -> i32 uext {
block0(v0: i32, v1: i32):
    jump block1(v0, v1)

block1(v2: i32, v3: i32):
    v4 = icmp_imm sgt v2, 0
	v5 = iadd_imm v2, -1
	v6 = iadd_imm v3, 3
    brif v4, block1(v5, v6), block2(v6)


block2(v7: i32):
    return v7
}

; run: %add_sum(0,0) == 3
; run: %add_sum(1,1) == 7
; run: %add_sum(10,2) == 35

;
; Disassembled:
; block0: ; offset 0x0
; echo =>2, =>0
; dup =>0, =>3
; ld i8, =>1
; call 0
; echo =>0, =>0
; st 
; ret 0