test compile precise-output
target scry32


function u0:4(i32, i32) system_v {
        sig0 = (i32, i32) -> i32 windows_fastcall
    
block0(v0: i32, v1: i32):
	v2 = load.i32 notrap aligned v1
	v3 = load.i32 notrap aligned v1+16
	v4 = call_indirect sig0, v0(v2, v3)
	store notrap aligned v4, v1
	return
}

; VCode:
; block0:
;   Echo(rds:, v(192), v(193), rss:, outs: [6, 0], )
;   Duplicate(rd1:, v(205), rd2:, v(206), rs:, v(193), out1: 0, out2: 7, )
;   Duplicate(rd1:, v(203), rd2:, v(204), rs:, v(205), out1: 0, out2: 2, )
;   Load(ty: Known(Uint(2)), rd:, v(202), rs:, v(203), out: 4, )
;   Const(ty: Known(Uint(2)), rd:, v(199), imm: 16, )
;   Alu2(var: Add, var_out Low, rds:, v(200), rss:, v(199), v(204), outs: [0], )
;   Load(ty: Known(Uint(2)), rd:, v(201), rs:, v(200), out: 1, )
;   Call(link:, v(197), fn_ptr:, v(192), trig: 0, )
;   CallArgs(link:, v(197), rets:, v(198), args:, v(202), v(201), )
;   Reorder(rd1:, v(207), rd2:, v(208), rs1:, v(206), rs2:, v(198), out: 0, )
;   Store(rd:, v(207), rs:, v(208), )
;   Ret(trig: 0, )

;
; Disassembled:
; block0: ; offset 0x0
; echo =>6, =>0
; dup =>0, =>7
; dup =>0, =>2
; ld u32, =>4
; const u32, 16
; add Low =>0
; ld u32, =>1
; call 0
; echo =>0, =>0
; st 
; ret 0
